# Clean and don't fail, then download and install Hugo-extended version 0.58.3
install:
  - rm -rf public || exit 0
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_extended_0.58.3_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

# Build the website using Hugo
script:
  - hugo

branches:
  only:
    - source

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  target_branch: master
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: source
