# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://edwardmpearce.github.io/"

# Title of your site
title = "Edward Pearce"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = "Copyright &copy; Edward Pearce {year}"

# Name of Academic theme folder in `themes/`.
theme = "academic"

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = true  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Get last modified date for content from Git?
enableGitInfo = true

paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true

[outputs]
  home = [ "HTML", "CSS", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).
  angledQuotes = false
  latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"


[params] 
  ############################
  ## Author Setup           ##
  ############################

  # Display name
  name = "Edward Pearce"
  
  # Role/position
  role = "Postgraduate Research Student"
  
  # Organizations/Affiliations
  #   Separate multiple entries with a comma, using the form: `[ {name="Org1", url=""}, {name="Org2", url=""} ]`.
  organizations = [ { name = "The University of Sheffield", url = "" } ]
  
  # Get user avatars from Gravatar.com? (true/false)
  gravatar = false


  ############################
  ## Contact Widget setup   ##
  ############################

  # Enter contact details (optional). To hide a field, clear it to "".
  email = "empearce1@sheffield.ac.uk"
  phone = ""
  address = "Hicks Building J14b, The University of Sheffield, Sheffield, S3 7RH, UK"

  # Office hours: use `<br>` to insert a line break, or set to "" to remove office hours
  #office_hours = """Monday 10:00 to 13:00<br>
  #                  Wednesday 09:00 to 10:00"""

  # Enter an optional link for booking appointments (e.g. calendly.com).
  #appointment_url = "https://calendly.com"

  # Contact links
  #   Set to `[]` to disable, or comment out unwanted lines with a hash `#`.
  contact_links = [
  #  {icon = "twitter", icon_pack = "fab", name = "DM Me", link = "https://twitter.com/edwardmpearce"},
  #  {icon = "skype", icon_pack = "fab", name = "Skype Me", link = "skype:echo123?call"},
  #  {icon = "keybase", icon_pack = "fab", name = "Chat on Keybase", link = "https://keybase.io/"},
  #  {icon = "comments", icon_pack = "fas", name = "Discuss on Forum", link = "https://discourse.gohugo.io"},
  #  {icon = "telegram", icon_pack = "fab", name = "Telegram Me", link = "https://telegram.me/@Telegram"},
  ]

  # Display a map.
  # To show your address on a map in the contact widget, you need to enter your latitude, longitude and choose
  # a map provider below.
  # To use Google Maps, set `map = 1` and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `map = 2`.
  # To use OpenStreetMap on a high traffic site, set `map = 3` and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  # To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.
  #
  # Map provider:
  #   0: No map
  #   1: Google Maps
  #   2: OpenStreetMap (Mapnik)
  #   3: OpenStreetMap (Mapbox)
  map = 0
  map_api_key = ""
  latitude = "37.4275"
  longitude = "-122.1697"
  zoom = 15

  ############################
  ## Plugins                ##
  ############################

  # Load CSS and JS plugins
  #   E.g. To load `/assets/css/custom.css`, set `plugins_css = ["custom"]`.
  #   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
  plugins_css = []
  plugins_js  = []
  

  ############################
  ## Site Setup             ##
  ############################ 
  # Documentation: https://sourcethemes.com/academic/

  # Color theme.
  #   Choose from `default`, `ocean`, `forest`, `dark`, `apogee`, `1950s`, `coffee`, `cupcake`.
  color_theme = "ocean"
  # Enable users to switch between day and night mode?
  day_night = true

  # Font style.
  #   Choose from `default`, `classic`, or `playfair`.
  font = "default"

  # Description for social sharing and search engines. If undefined, superuser role is used in place.
  description = "Edward Pearce's personal website"

  # Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
  sharing_image = "icon-192.png"

  # Twitter username (without @). Used when a vistor shares your site on Twitter.
  twitter = "edwardmpearce"

  # Diplay a logo in navigation bar rather than title (optional).
  #   To enable, place an image in `static/img/` and reference its filename below. To disable, set the value to "".
  logo = ""

  # Enable global source code highlighting? true/false
  # Documentation: https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
  highlight = true
  # highlight_languages = ["r"]  # Add support for highlighting additional languages
  highlight_style = "solarized-dark"  # For supported styles, see https://cdnjs.com/libraries/highlight.js/

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = true

  # Privacy pack
  #   Show a cookie consent message to visitors
  #   Anonymize IP in Google Analytics (if enabled)
  privacy_pack = false

  # Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Jan 2, 2006"
  #   Examples: "3:04 pm" or "15:04"
  time_format = "3:04 PM"
  
  # Align the main menu to the right of the page? (true/false)
  menu_align_right = false

  # Show estimated reading time for posts? (true/false)
  reading_time = true

  # Display comment count (if commenting enabled in config.toml)? (true/false)
  comment_count = true

  # Display next/previous section pager? (true/false)
  section_pager = false

  # Enable in-built social sharing buttons? (true/false)
  sharing = false

  # Configuration of publication pages.
  [params.publications]
    # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "January 2006"

    # Citation style ("apa" or "mla")
    citation_style = "apa"

  # Configuration of project pages.
  [params.projects]
    # Views for associated content.
    #   1: List
    #   2: Compact
    #   3: Card
    #   4: Citation (publications only)
    post_view = 2
    publication_view = 2
    talk_view = 2

  # Search.
  [params.search]
    # Search provider:
    #   0: No search engine
    #   1: Academic (built-in)
    #   2: Algolia (https://www.algolia.com)
    engine = 1

    # Configuration of Algolia search engine.
    # Paste the values from your Algolia dashboard.
    [params.search.algolia]
      app_id = ""
      api_key = ""
      index_name = ""
      show_logo = false 

  # Footer social buttons
  # For available icons, see: https://sourcethemes.com/academic/docs/widgets/#icons
  #   For an email link, use "fas" icon pack, "envelope" icon, and a link in the
  #   form "mailto:your-email@example.com" or "#contact" for contact widget.
  [[params.footerbutton]]
    icon = "twitter"
    icon_pack = "fab"
    link = "https://twitter.com/edwardmpearce" 

  [[params.footerbutton]]
	icon = "linkedin"
    icon_pack = "fab"
    link = "https://www.linkedin.com/in/edwardm-pearce/"
	
  [[params.footerbutton]]
    icon = "github"
    icon_pack = "fab"
    link = "https://github.com/edwardmpearce"
  
  
############################
## Menus                  ##
############################
  
# Navigation Links
[menus]
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

  [[menus.main]]
  name = "Home"
  url = "#about"
  weight = 1
  
  [[menus.main]]
  name = "Activities"
  url = "/activities/"
  weight = 2
  
#  [[menus.main]]
#  name = "Talks"
#  url = "/talk/"
#  weight = 3  

#  [[menus.main]]
#  name = "Notes"
#  url = "/notes/"
#  weight = 4

#  [[menus.main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 5

#  [[menus.main]]
#  name = "Blog"
#  url = "#posts"
#  weight = 6
  
  [[menus.main]]
  name = "Teaching"
  url = "/teaching/"
  weight = 7

#  [[menus.main]]
#  name = "Publications"
#  url = "#featured"
#  weight = 40

#  [[menus.main]]
#  name = "Tutorials"
#  url = "/tutorial/"
#  weight = 50
  
  [[menus.main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[menus.main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
  

############################
## Languages              ##
############################  
  
# Languages
[languages]
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
  [languages.en]
    languageCode = "en-us"
    contentDir = "content/en"
  
# Configure the Chinese version of the site.
  [languages.zh]
    languageCode = "zh-Hans"
    contentDir = "content/zh"
    title = "罗毅华"
	
    [languages.zh.params]
      description = "罗毅华的个人网站"
	  # Display name
      name = "罗毅华" 
	  
	  # Role/position
      role = "博士生"

      # Organizations/Affiliations
      #   Separate multiple entries with a comma, using the form: `[ {name="Org1", url=""}, {name="Org2", url=""} ]`.
      organizations = [ { name = "谢菲尔德大学", url = "" } ]
	
	# Navigation Links
    [[languages.zh.menus.main]]
      name = "主页"
      url = "#about"
      weight = 1
	  
    [[languages.zh.menus.main]]
      name = "活动"
      url = "/activities/"
      weight = 2

    [[languages.zh.menus.main]]
      name = "教学"
      url = "/teaching/"
      weight = 3

#    [[languages.zh.menus.main]]
#      name = "笔记"
#      url = "/notes/"
#      weight = 4

#    [[languages.zh.menus.main]]
#      name = "博客"
#      url = "#posts"
#      weight = 5

    [[languages.zh.menus.main]]
      name = "联系方式"
      url = "#contact"
      weight = 80
	
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
    [[languages.zh.menus.main]]
      name = "简历"
      url = "../files/cv20190412.pdf"
      weight = 70 